version: 0.2

phases:
    install: 
        commands: 
            - npm ci
    build:
        commands:
            - npm run build 
            - codebuild-breakpoint
    post_build:
        commands:
            - npm test -- --coverage

reports:
    UnitTests:
        files:
            - "test-report.xml"
        file-format: "JUNITXML"
    CoverageTests:
        files:
            - "clover.xml"
        file-format: "CLOVERXML"
