version: 0.2

phases:
    install: 
        commands: 
            - npm ci
    build:
        commands:
            - npm run build 
            - codebuild-breakpoint
    post_build:
        commands:
            - npm run test


